'use strict';
const STAGES=[
{id:'TILT-001',title:'First Tilt',size:5,walls:[{x:1,y:1},{x:3,y:3}],blocks:[{x:0,y:2,c:0}],goals:[{x:4,y:2,c:null}],rule:'ALL_IN',best:1},
{id:'TILT-002',title:'One More',size:5,walls:[{x:2,y:1},{x:2,y:3}],blocks:[{x:0,y:1,c:0},{x:0,y:3,c:0}],goals:[{x:4,y:1,c:null},{x:4,y:3,c:null}],rule:'ALL_IN',best:2},
{id:'TILT-003',title:'Walls',size:6,walls:[{x:2,y:1},{x:2,y:2},{x:3,y:3},{x:3,y:4}],blocks:[{x:0,y:0,c:0}],goals:[{x:5,y:5,c:null}],rule:'ALL_IN',best:3},
{id:'TILT-004',title:'Crossing',size:6,walls:[{x:2,y:2},{x:3,y:2},{x:2,y:3},{x:3,y:3}],blocks:[{x:0,y:2,c:0},{x:5,y:3,c:1}],goals:[{x:5,y:0,c:null},{x:0,y:5,c:null}],rule:'ALL_IN',best:3},
{id:'TILT-005',title:'Order',size:6,walls:[{x:2,y:1},{x:2,y:4},{x:4,y:2},{x:4,y:3}],blocks:[{x:0,y:1,c:0},{x:0,y:4,c:1}],goals:[{x:5,y:2,c:0},{x:5,y:3,c:1}],rule:'COLOR_IN',best:4},
{id:'TILT-006',title:'Blocked',size:7,walls:[{x:3,y:1},{x:3,y:2},{x:3,y:4},{x:3,y:5}],blocks:[{x:1,y:0,c:0},{x:5,y:6,c:1}],goals:[{x:6,y:1,c:0},{x:0,y:5,c:1}],rule:'COLOR_IN',color:1,best:4},
{id:'TILT-007',title:'Around',size:7,walls:[{x:2,y:2},{x:3,y:2},{x:4,y:2},{x:2,y:4},{x:3,y:4},{x:4,y:4}],blocks:[{x:0,y:3,c:0}],goals:[{x:6,y:3,c:null}],rule:'ALL_IN',best:4},
{id:'TILT-008',title:'Two Turns',size:7,walls:[{x:2,y:0},{x:2,y:1},{x:4,y:5},{x:4,y:6}],blocks:[{x:0,y:0,c:0},{x:6,y:6,c:1}],goals:[{x:6,y:2,c:null},{x:0,y:4,c:null}],rule:'ALL_IN',best:4},
{id:'TILT-009',title:'Read Ahead',size:7,walls:[{x:3,y:1},{x:3,y:2},{x:3,y:4},{x:3,y:5},{x:1,y:3},{x:5,y:3}],blocks:[{x:0,y:0,c:0},{x:6,y:6,c:1}],goals:[{x:0,y:6,c:null},{x:6,y:0,c:null}],rule:'ALL_IN',best:5},
{id:'TILT-010',title:'Chain',size:7,walls:[{x:2,y:1},{x:4,y:1},{x:2,y:5},{x:4,y:5}],blocks:[{x:1,y:3,c:0},{x:3,y:3,c:1},{x:5,y:3,c:2}],goals:[{x:6,y:3,c:null}],rule:'SELECT',target:0,best:3},
{id:'TILT-011',title:'Goal Is The Puzzle',size:8,walls:[{x:3,y:1},{x:4,y:1},{x:3,y:6},{x:4,y:6},{x:2,y:3},{x:2,y:4}],blocks:[{x:0,y:0,c:0},{x:7,y:7,c:1}],goals:[{x:7,y:1,c:null},{x:0,y:6,c:null}],rule:'ALL_IN',best:5},
{id:'TILT-012',title:'Blue Only',size:8,walls:[{x:3,y:2},{x:4,y:2},{x:3,y:5},{x:4,y:5}],blocks:[{x:0,y:3,c:0},{x:7,y:3,c:1},{x:2,y:0,c:1}],goals:[{x:7,y:6,c:1}],rule:'COLOR_IN',color:1,best:5},
{id:'TILT-013',title:'Match',size:8,walls:[{x:2,y:2},{x:5,y:2},{x:2,y:5},{x:5,y:5}],blocks:[{x:0,y:0,c:0},{x:7,y:0,c:0},{x:0,y:7,c:1},{x:7,y:7,c:1}],goals:[{x:3,y:3,c:0},{x:4,y:4,c:1}],rule:'MATCH',best:6},
{id:'TILT-014',title:'Form',size:8,walls:[{x:1,y:3},{x:2,y:3},{x:5,y:3},{x:6,y:3},{x:1,y:4},{x:2,y:4},{x:5,y:4},{x:6,y:4}],blocks:[{x:0,y:0,c:0},{x:3,y:0,c:0},{x:7,y:0,c:0}],goals:[{x:3,y:7,c:null}],rule:'ALL_IN',best:5},
{id:'TILT-015',title:'Reverse',size:8,walls:[{x:3,y:1},{x:4,y:1},{x:3,y:2},{x:4,y:2},{x:3,y:5},{x:4,y:5},{x:3,y:6},{x:4,y:6}],blocks:[{x:0,y:0,c:0},{x:7,y:7,c:1}],goals:[{x:0,y:7,c:null},{x:7,y:0,c:null}],rule:'ALL_IN',best:5},
{id:'TILT-016',title:'Which First?',size:8,walls:[{x:2,y:1},{x:2,y:2},{x:2,y:3},{x:5,y:4},{x:5,y:5},{x:5,y:6}],blocks:[{x:0,y:0,c:0},{x:7,y:0,c:1},{x:0,y:7,c:2}],goals:[{x:7,y:7,c:2}],rule:'SELECT',target:2,best:5},
{id:'TILT-017',title:'Heavy',size:8,walls:[{x:2,y:2},{x:2,y:3},{x:5,y:4},{x:5,y:5}],blocks:[{x:0,y:0,c:0,w:2,h:1},{x:6,y:7,c:1}],goals:[{x:7,y:0,c:null},{x:0,y:7,c:null}],rule:'ALL_IN',best:6},
{id:'TILT-018',title:'Whole Board',size:9,walls:[{x:4,y:1},{x:4,y:2},{x:4,y:6},{x:4,y:7},{x:2,y:4},{x:3,y:4},{x:5,y:4},{x:6,y:4}],blocks:[{x:0,y:0,c:0},{x:8,y:0,c:1},{x:0,y:8,c:2},{x:8,y:8,c:3}],goals:[{x:4,y:4,c:null}],rule:'SELECT',target:3,best:6},
{id:'TILT-019',title:'Compare',size:9,walls:[{x:3,y:2},{x:5,y:2},{x:3,y:3},{x:5,y:3},{x:3,y:5},{x:5,y:5},{x:3,y:6},{x:5,y:6}],blocks:[{x:0,y:0,c:0},{x:8,y:0,c:1},{x:0,y:8,c:2}],goals:[{x:8,y:8,c:null},{x:0,y:4,c:null}],rule:'ALL_IN',best:7},
{id:'TILT-020',title:'Aha!',size:9,walls:[{x:4,y:0},{x:4,y:1},{x:4,y:3},{x:4,y:5},{x:4,y:7},{x:4,y:8},{x:1,y:4},{x:2,y:4},{x:6,y:4},{x:7,y:4}],blocks:[{x:0,y:0,c:0},{x:8,y:0,c:1},{x:0,y:8,c:2},{x:8,y:8,c:3}],goals:[{x:4,y:4,c:null}],rule:'SELECT',target:2,best:8}
];
const DIR={UP:[0,-1],DOWN:[0,1],LEFT:[-1,0],RIGHT:[1,0]};
const COLORS=['#8ee6ff','#9aa8ff','#8ff0b3','#ffcf8b'];
const state={stage:0,mode:'TITLE',blocks:[],walls:new Set(),goals:[],moves:0,history:[],unlocked:1,clear:{},control:'SWIPE'};
const $=id=>document.getElementById(id); const board=$('board'); const toastEl=$('toast');
function load(){try{const s=JSON.parse(localStorage.getItem('tiltSave')||'{}');state.unlocked=Math.max(1,s.unlocked||1);state.clear=s.clear||{}}catch{}}
function save(){localStorage.setItem('tiltSave',JSON.stringify({unlocked:state.unlocked,clear:state.clear}))}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(name).classList.add('active');state.mode=name==='gameScreen'?'PLAYING':name==='stageScreen'?'STAGES':'TITLE';if(name==='stageScreen')renderStages()}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>toastEl.classList.remove('show'),1300)}
function makeStage(i){const s=STAGES[i];state.stage=i;state.blocks=s.blocks.map((b,id)=>({id,x:b.x,y:b.y,w:b.w||1,h:b.h||1,c:b.c??0}));state.walls=new Set(s.walls.map(p=>`${p.x},${p.y}`));state.goals=s.goals.map(g=>({...g}));state.moves=0;state.history=[];state.mode='PLAYING';$('stageTitle').textContent=`${i+1}. ${s.title}`;updateMeta();$('nextBtn').style.display='none';$('clear').classList.remove('show');show('gameScreen');requestAnimationFrame(render)}
function updateMeta(){const s=STAGES[state.stage],best=state.clear[s.id]?.moves;$('stageMeta').textContent=`${state.moves}手 · BEST ${best??'—'} · OPT ${s.best}`}
function render(){const s=STAGES[state.stage];board.innerHTML='';board.style.gridTemplateColumns=`repeat(${s.size},1fr)`;board.style.gridTemplateRows=`repeat(${s.size},1fr)`;for(let i=0;i<s.size*s.size;i++){const el=document.createElement('div');el.className='cell';board.appendChild(el)}
 for(const w of state.walls){const [x,y]=w.split(',').map(Number);const el=document.createElement('div');el.className='wall';el.style.gridColumn=x+1;el.style.gridRow=y+1;board.children[y*s.size+x].appendChild(el)}
 for(const g of state.goals){const el=document.createElement('div');el.className='goal';if(g.c!=null){el.style.borderColor=COLORS[g.c%COLORS.length];el.style.boxShadow=`0 0 18px ${COLORS[g.c%COLORS.length]}`};el.style.gridColumn=g.x+1;el.style.gridRow=g.y+1;board.children[g.y*s.size+g.x].appendChild(el)}
 const rect=board.getBoundingClientRect(),cw=rect.width/s.size,ch=rect.height/s.size;
 for(const b of state.blocks){const el=document.createElement('div');el.className='block';const color=COLORS[b.c%COLORS.length];el.style.setProperty('--block',color);el.style.setProperty('--glow',color);el.style.left=`${b.x*cw+4}px`;el.style.top=`${b.y*ch+4}px`;el.style.width=`${Math.max(8,b.w*cw-8)}px`;el.style.height=`${Math.max(8,b.h*ch-8)}px`;el.dataset.id=b.id;board.appendChild(el)} }
function cells(b,nx=b.x,ny=b.y){const a=[];for(let y=0;y<b.h;y++)for(let x=0;x<b.w;x++)a.push([nx+x,ny+y]);return a}
function valid(b,nx,ny){const s=STAGES[state.stage];for(const [x,y] of cells(b,nx,ny)){if(x<0||y<0||x>=s.size||y>=s.size||state.walls.has(`${x},${y}`))return false;for(const o of state.blocks)if(o.id!==b.id&&cells(o).some(([ox,oy])=>ox===x&&oy===y))return false}return true}
function snapshot(){return JSON.stringify({blocks:state.blocks,moves:state.moves})}
function restore(str){const v=JSON.parse(str);state.blocks=v.blocks;state.moves=v.moves;updateMeta();render()}
function goalHit(b){return state.goals.some(g=>cells(b).some(([x,y])=>x===g.x&&y===g.y)&& (g.c==null||g.c===b.c))}
function move(dir){if(state.mode!=='PLAYING')return;const before=snapshot(),d=DIR[dir],ordered=[...state.blocks].sort((a,b)=>dir==='DOWN'?b.y-a.y:dir==='UP'?a.y-b.y:dir==='RIGHT'?b.x-a.x:a.x-b.x);let moved=false;for(const b of ordered){while(valid(b,b.x+d[0],b.y+d[1])){b.x+=d[0];b.y+=d[1];moved=true}}
 const s=STAGES[state.stage];let removed=[];for(const b of state.blocks){if(goalHit(b) && (s.rule!=='SELECT'||b.c===s.target))removed.push(b.id)}if(removed.length){state.blocks=state.blocks.filter(b=>!removed.includes(b.id));moved=true}
 if(!moved)return;state.history.push(before);if(state.history.length>50)state.history.shift();state.moves++;updateMeta();render();if(removed.length)tone('goal');if(clearNow())complete()}
function clearNow(){const s=STAGES[state.stage];if(s.rule==='SELECT')return !state.blocks.some(b=>b.c===s.target);if(s.rule==='COLOR_IN')return !state.blocks.some(b=>b.c===s.color);return state.blocks.length===0}
function complete(){state.mode='CLEAR';const s=STAGES[state.stage],stars=state.moves<=s.best?3:state.moves<=s.best+2?2:1,old=state.clear[s.id];if(!old||state.moves<old.moves)state.clear[s.id]={moves:state.moves,stars};state.unlocked=Math.max(state.unlocked,Math.min(STAGES.length,state.stage+2));save();renderStages();$('clear').classList.remove('show');void $('clear').offsetWidth;$('clear').classList.add('show');$('nextBtn').style.display=state.stage<STAGES.length-1?'block':'none';tone('clear')}
function renderStages(){const grid=$('stageGrid');grid.innerHTML='';let done=0;STAGES.forEach((s,i)=>{const d=state.clear[s.id],ok=i<state.unlocked;if(d)done++;const b=document.createElement('button');b.className='stageBtn '+(ok?'':'locked')+' '+(d?'done':'');b.disabled=!ok;b.innerHTML=`<strong>${i+1}</strong><span>${ok?s.title:'LOCKED'}</span><span class="stars">${d?'★'.repeat(d.stars)+'☆'.repeat(3-d.stars):' '}</span>`;b.onclick=()=>makeStage(i);grid.appendChild(b)});$('progress').textContent=`${done} / ${STAGES.length}`}
function undo(){if(!state.history.length){toast('戻せる手がありません');return}restore(state.history.pop())}
function restart(){makeStage(state.stage)}
function tone(kind){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ac=new A(),o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);const t=ac.currentTime;const f=kind==='clear'?440:520;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(kind==='clear'?880:650,t+.16);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.05,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.18);o.start(t);o.stop(t+.19)}catch{}}
let sx=null,sy=null;board.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY});board.addEventListener('pointerup',e=>{if(sx==null)return;const dx=e.clientX-sx,dy=e.clientY-sy;sx=sy=null;if(Math.hypot(dx,dy)<24)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?'RIGHT':'LEFT'):(dy>0?'DOWN':'UP'))});
function onOrientation(e){if(state.mode!=='PLAYING'||state.control!=='TILT')return;const g=e.gamma||0,b=e.beta||45;if(Math.abs(g)>25&&Math.abs(g)>Math.abs(b-45)){move(g>0?'RIGHT':'LEFT')}else if(Math.abs(b-45)>25){move(b>45?'DOWN':'UP')}}
async function enableTilt(){if(!('DeviceOrientationEvent' in window)){state.control='SWIPE';return}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw new Error()}state.control='TILT';toast('TILT操作 ON')}catch{state.control='SWIPE';toast('スワイプ操作でプレイ')}}
$('playBtn').onclick=async()=>{load();makeStage(0);await enableTilt()};$('backBtn').onclick=()=>show('titleScreen');$('stagesBtn').onclick=()=>show('stageScreen');$('undoBtn').onclick=undo;$('restartBtn').onclick=restart;$('nextBtn').onclick=()=>makeStage(Math.min(STAGES.length-1,state.stage+1));$('pauseBtn').onclick=()=>{$('pauseOverlay').classList.add('active');state.mode='PAUSE'};$('resumeBtn').onclick=()=>{$('pauseOverlay').classList.remove('active');state.mode='PLAYING'};
window.addEventListener('deviceorientation',onOrientation);window.addEventListener('resize',()=>state.mode==='PLAYING'&&render());document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='PLAYING'){state.mode='PAUSE';$('pauseOverlay').classList.add('active')}});load();renderStages();
